### ISSUE TITLE
Consider an enum based constructor

### ISSUE THREAD

**Issue by Nemo157** [maidsafe/lru_time_cache#61]
In my particular use case I want to provide an api taking in an optional ttl and capacity and constructing an LRU cache based on them. Currently I'm using code similar to the following for that:

```rust
pub enum CacheLimit {
  Capacity(usize),
  TimeToLive(Duration),
  TimeToLiveAndCapacity(Duration, usize),
}

match options.cache_limit {
  CacheLimit::Capacity(capacity) => LruCache::with_capacity(capacity),
  CacheLimit::TimeToLive(ttl) => LruCache::with_expiry_duration(ttl),
  CacheLimit::TimeToLiveAndCapacity(ttl, capacity) => LruCache::with_expiry_duration_and_capacity(ttl, capacity),
}
```

This seems like something that could be added to the library for anyone else that would want to provide a similar API, maybe the method

```rust
impl LruCache {
  pub fn with_limit(limit: CacheLimit) -> LruCache;
}
```

**Comment by dirvine** [comment]
Do you mean a trait to select the constructor you want from an enum? I am not sure I understand the use case here. I maybe missing something though, perhaps you can elucidate a bit further. This looks like it is best outside the library as a specific case perhaps. Thanks for the feedback, lets bash it out a bit.

**Comment by Nemo157** [comment]
I have a web request handler that can use a cache to speed up handling some requests. Instead of having hard coded configuration for the cache I want to be able to pass in runtime config loaded from a config file. This would include switching between capacity/duration/combined limits based on the config values.

When constructing the handler I pass in a `CacheLimit` enum so the external code doesn't need to know the exact caching implementation. But then because `LruCache` has different constructor methods for the different ways of specifying the limit I need to choose which of these to use.

Runtime configuration seems a common enough use case that I thought it may be useful to support something like this natively in the library. What I was trying to say with the last paragraph was that I thought adding a similar enum, along with an `LruCache` constructor that takes the enum in to specify its capacity limits, could be useful for other users as well.

Looking at the actual code I see that the constructors are basically equivalent to using `usize::MAX` and `Duration::max_value()` for the limit you don't care about. I could probably just take in both values as a config option and default them if not specified. I guess I was assuming that since there were actually separate constructors for the different cases they would be doing more than just defaulting the non-provided value.

**Comment by dirvine** [comment]
Ah I see, if you can try with that pattern and run into any issues let us know and we will look farther into accommodating your use case as best as it can be. Thanks for the feedback in the meantime and good luck with the app. Any PR's will be appreciated that improves this lib.
