### ISSUE TITLE
Lru time cache should have a more standard API

### ISSUE THREAD

**Issue by canndrew** [maidsafe/lru_time_cache#66]
It's odd that `LruTimeCache` has a method to clone all it's elements out into a `Vec`. Standard library collections don't have methods like this. To clone a `HashMap` into a `Vec` you'd write:

    my_hash_map.iter().map(|(k, v)| (k.clone(), v.clone())).collect()

Although if someone did this in practice (rather than just using the iterator) they'd probably be doing something wrong.

`LruTimeCache`'s API should be changed to mirror that of `HashMap` as closely as is appropriate.

**Comment by dirvine** [comment]
!00% agree here.

**Comment by canndrew** [comment]
I just noticed that the TODO list in the README already says this.

**Comment by andrebeat** [comment]
There's now a method [`peek_iter`](http://docs.maidsafe.net/lru_time_cache/master/lru_time_cache/struct.LruCache.html#method.peek_iter) which returns an iterator (that doesn't update timestamps), so I think this can be closed.

**Comment by afck** [comment]
Thank you, @andrebeat! With #77 merged, I'm closing this now.
