### ISSUE TITLE
change `key: &Key` argument to use `Borrow` trait

### ISSUE THREAD

**Issue by loggerhead** [maidsafe/lru_time_cache#80]
For example, the following code is not support:

```rust
let cache: LruCache<String, String> = LruCache::with_capacity(1);
cache.contains_key("foo");
```

Consider change the method declaration from

```rust
fn contains_key(&self, key: &Key) -> bool 
```

to 

```rust
fn contains_key<Q: ?Sized>(&self, k: &Q) -> bool 
    where Key: Borrow<Q>, Q: Ord
```

**Comment by afck** [comment]
I agree, also with #81! In general, we should get the API more in line with the standard library's maps.
PRs are welcome. :slightly_smiling_face:
